### PR TITLE
Fixes flutter_svg latest version requiring a non null clipBehavior field.

### LINKED ISSUE #368: [BUG]: SvgPicture.asset generated code not compatible with latest flutter_svg
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

5.2.0

### Command type

build_runner (Default)

### What happened?

Generated code has:
`The argument type 'Clip?' can't be assigned to the parameter type 'Clip'. `

This is casued by flutter_svg changing the parameter Clip? to Clip: clipBehavior = Clip.hardEdge and removing the deprecated annotation.

https://github.com/dnfield/flutter_svg/blame/master/lib/svg.dart#L181

See flutter_svg 2.0.4

### Relevant a pubspec.yaml.

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jetpeter**
## What does this change?

Fixes flutter_svg latest version requiring a non null clipBehavior field.

Fixes #368 

## Type of change

Please delete options that are not relevant.

- [X ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [X ] Make sure to open a GitHub issue as a bug/feature request before writing your code! That way we can discuss the change, evaluate designs, and agree on the general idea
  - [ ] Ensure the tests (`melos run unit:test`)
  - [ ] Ensure the analyzer and formatter pass (`melos run format` to automatically apply formatting)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by jetpeter** [comment]
Tests are broken for this because they expect updated files in the `tests_resources/actual_data` file.  Is there a command that generated all of those test files, with all the different parameters? I will update this with the correct test data, but I assume it does not need to be manually done.

**Comment by wasabeef** [comment]
@jetpeter 
Thank you, I'll check this PR.

**Comment by jfacoustic** [comment]
I tested your commit, but it doesn't seem to be generating the code with the nonNullable clip behavior.  Any ideas what might be going on?

Added it to my pubspec like so:

```
  flutter_gen_runner:
    git:
      url: https://github.com/jetpeter/flutter_gen
      path: packages/runner
      ref: 785161759cf07319c59d5ecc9de4ef66662bcd95
```

**Comment by noga-dev** [comment]
> I tested your commit, but it doesn't seem to be generating the code with the nonNullable clip behavior. Any ideas what might be going on?
> 
> Added it to my pubspec like so:
> 
> ```
>   flutter_gen_runner:
>     git:
>       url: https://github.com/jetpeter/flutter_gen
>       path: packages/runner
>       ref: 785161759cf07319c59d5ecc9de4ef66662bcd95
> ```

Can confirm. I basically had to delete the line ```clipBehavior: clipBehavior,``` from ```SvgGenImage.svg``` in ```assets.gen.dart```

**Comment by jetpeter** [comment]
> I tested your commit, but it doesn't seem to be generating the code with the nonNullable clip behavior. Any ideas what might be going on?
> 
> Added it to my pubspec like so:
> 
> ```
>   flutter_gen_runner:
>     git:
>       url: https://github.com/jetpeter/flutter_gen
>       path: packages/runner
>       ref: 785161759cf07319c59d5ecc9de4ef66662bcd95
> ```

Change was not made to flutter_gen_runner. It was made to flutter_gen_core.  To get the fix you need to add
```
dependency_overrides:
  flutter_gen_core:
    git:
      url: https://github.com/jetpeter/flutter_gen
      path: packages/core
      ref: 785161759cf07319c59d5ecc9de4ef66662bcd95
```
below your dev_dependencies: block.

**Comment by noga-dev** [comment]
> > I tested your commit, but it doesn't seem to be generating the code with the nonNullable clip behavior. Any ideas what might be going on?
> > Added it to my pubspec like so:
> > ```
> >   flutter_gen_runner:
> >     git:
> >       url: https://github.com/jetpeter/flutter_gen
> >       path: packages/runner
> >       ref: 785161759cf07319c59d5ecc9de4ef66662bcd95
> > ```
> 
> Change was not made to flutter_gen_runner. It was made to flutter_gen_core. To get the fix you need to add
> 
> ```
> dependency_overrides:
>   flutter_gen_core:
>     git:
>       url: https://github.com/jetpeter/flutter_gen
>       path: packages/core
>       ref: 785161759cf07319c59d5ecc9de4ef66662bcd95
> ```
> 
> below your dev_dependencies: block. You don't actually need to override flutter_gen_runner since there are not changes to it.

Oops, didn't notice the changes we're in the core package. Thanks. LGTM.

**Review by szelemeh — APPROVED** [review]

**Review by wasabeef — APPROVED** [review]

**Comment by wasabeef** [comment]
@jetpeter @szelemeh @jetpeter @noga-dev 

Thank you, I will release a new version today.

**Comment by wasabeef** [comment]
@jetpeter @jfacoustic @noga-dev @szelemeh  

I just released `v5.3.0`.  Sorry I kept you waiting.

**Pull request merged**
