### PR TITLE
Added 'gen_for_package:true/false' param to support asset generation for a package

### PR DESCRIPTION
**Pull request by urvesh-open**
### Why fix is required?
Currently if we use **fluttergen** then the asset path generated won't work for packages as it expects assets path from `packages/<package_name>/<asset_path>`

### What is changed/added?
Added flutter package support:
- By added `gen_for_package:true` to the fluttergen config it will generate assets with path that can be resolved in a package.

### CODE REVIEW

**Comment by wasabeef** [comment]
@urvesh-open 
Thank you.

Is the pr purpose the same? https://github.com/FlutterGen/flutter_gen/pull/162

**Comment by urvesh-open** [comment]
> @urvesh-open Thank you.
> 
> Is the pr purpose the same? #162

Oops. Yes @wasabeef it is solving the same feature request only the way of implementation is different in both the PRs

**Comment by urvesh-open** [comment]
@wasabeef do I close this PR? As [#162](https://github.com/FlutterGen/flutter_gen/pull/162) is resolving same feature request only the implementation is different.

**Comment by wasabeef** [comment]
@urvesh-open 
Can you wait for a while?
I'm thinking about these implementations.

**Comment by urvesh-open** [comment]
> @urvesh-open Thank you. Can you wait for a while? I'm thinking about these implementations.

Got it. Will keep it open

**Comment by wasabeef** [comment]
@urvesh-open 
Thank you very much for your PR. But we solved the issue in another way.  Please use v4.2.1. 🙏

**Pull request closed without merging**
