### PR TITLE
➖ Thin & upgrade dependencies

### LINKED ISSUE #408: [FR]: Thin & Upgrade dependencies
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

- Dependencies constraints are weirdly configured in packages, such as `test: '>=1.16.0 <2.0.0'` which should be replaced by `test: ^1.16.0`
- Dependencies like `collection` are configured as a fixed version, which breaks development between SDK versions.
- `flutter_lints` is used but packages are only involved with Dart, `lints` should be used instead.
- `sdk` constraint can be updated to allow 3.x even though the SDK is not strictly force packages to obey them.
- Too many packages are used in the example (for compability reason?) which is redundant.

### Describe the solution

Reorg and improve dependencies.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AlexV525**
## What does this change?

Fixes #408.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [ ] Make sure to open a GitHub issue as a bug/feature request before writing your code! That way we can discuss the change, evaluate designs, and agree on the general idea
  - [x] Ensure the tests (`melos run unit:test`)
  - [x] Ensure the analyzer and formatter pass (`melos run format` to automatically apply formatting)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by shilangyu** [comment]
What is the status here? This PR includes removal of analyzer dep which will fix issues with flutter_gen blocking the analyzer version (#414).

**Comment by AlexV525** [comment]
Maybe @bramp can help with the review process?

**Comment by jtdLab** [comment]
Any updates ?

**Comment by AlexV525** [comment]
cc @lcdsmao

**Comment by shilangyu** [comment]
Who is the current maintainer of `flutter_gen`? Or who has push/publish rights for this repo? It is quite unfortunate as this is blocking the community from upgrading their dependencies and this PR would fix the issue.

**Comment by wasabeef** [comment]
@AlexV525 @shilangyu 
We're contacting a developer to increase more maintainers.

**Pull request merged**
