### PR TITLE
feat: support flutter_svg 2.0.0

### PR DESCRIPTION
**Pull request by lcdsmao**
## What does this change?

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #<issue_number_goes_here> 🎯

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open a GitHub issue as a bug/feature request before writing your code! That way we can discuss the change, evaluate designs, and agree on the general idea
  - [ ] Ensure the tests (`melos run unit:test`)
  - [ ] Ensure the analyzer and formatter pass (`melos run format` to automatically apply formatting)
- [ ] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by Harishwarrior** [comment]
Hi, how to use this branch?

**Comment by wasabeef** [comment]
@lcdsmao Thank you.

**Comment by jayjah** [comment]
Do you have any timeline to merge and publish (to pub.dev) this PR?

**Comment by lcdsmao** [comment]
@wasabeef 

Sorry, I merged via App.
Please review it.🥲

**Comment by suxoikorm** [comment]
@wasabeef Hello. This PR led to the fact that my generation broke. It generates a colorFilter no matter what version of flutter_svg I have. Such changes should be made in major versions.

**Comment by wasabeef** [comment]
@suxoikorm 

Sorry for the lack of explanation.
I should have put it in the RELEASE.md.

**Pull request merged**
